/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech)
 * (7.14.0). https://openapi-generator.tech Do not edit the class manually.
 */
package de.gematik.demis.ars.service.api;

/*-
 * #%L
 * Antibiotic-Resistance-Surveillance-Service
 * %%
 * Copyright (C) 2025 - 2026 gematik GmbH
 * %%
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the
 * European Commission – subsequent versions of the EUPL (the "Licence").
 * You may not use this work except in compliance with the Licence.
 *
 * You find a copy of the Licence in the "Licence" file or at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * In case of changes by gematik find details in the "Readme" file.
 *
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik,
 * find details in the "Readme" file.
 * #L%
 */

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;
import static org.springframework.http.MediaType.APPLICATION_XML_VALUE;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.WebRequest;

@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2025-08-05T17:25:05.601689573+02:00[Europe/Berlin]",
    comments = "Generator version: 7.14.0")
@Validated
@Tag(name = "notifications", description = "Submit antibiotic resistance notifications.")
public interface NotificationsApi {

  String MEDIA_TYPE_FHIR_JSON = "application/fhir+json";

  /**
   * POST /fhir/$process-notification : Processes an ARS notification
   *
   * @param authorization (required)
   * @param contentType Tells whether the request body is in JSON or XML format. (required)
   * @param body (required)
   * @return Processing response.
   */
  @Operation(
      operationId = "fhirProcessNotificationPost",
      summary = "Processes an ARS notification",
      description =
          """
          Accepts a FHIR R4 Bundle representing an antibiotic resistance notification and processes it.

          The response content type mirrors the request serialisation format unless \
          the Accept header explicitly requests a different FHIR format.
          """,
      tags = {"notifications"},
      responses = {
        @ApiResponse(
            responseCode = "200",
            description =
                "Notification accepted and stored. "
                    + "The body is a FHIR Parameters resource containing the assigned "
                    + "bundle identifier, specimen identifiers and the validation outcome.",
            content = {
              @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object")),
              @Content(mediaType = "application/fhir+xml", schema = @Schema(type = "string"))
            }),
        @ApiResponse(
            responseCode = "400",
            description =
                "Bad request – e.g. missing request body, fatal FHIR validation errors "
                    + "(FHIR_VALIDATION_FATAL) or a missing required resource "
                    + "(MISSING_RESOURCE).",
            content =
                @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object"))),
        @ApiResponse(
            responseCode = "401",
            description =
                "Unauthorized – the Authorization header is absent or the token is invalid.",
            content =
                @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object"))),
        @ApiResponse(
            responseCode = "415",
            description =
                "Unsupported Media Type – no Content-Type header was provided "
                    + "or the content type is not a supported FHIR format.",
            content =
                @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object"))),
        @ApiResponse(
            responseCode = "422",
            description =
                "Unprocessable Content – the bundle failed FHIR profile validation "
                    + "(FHIR_VALIDATION_ERROR) or the patient pseudonyms are not unique "
                    + "(INVALID_PSEUDONYMS).",
            content =
                @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object"))),
        @ApiResponse(
            responseCode = "500",
            description = "Internal Server Error – an unexpected server-side error occurred.",
            content =
                @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object"))),
        @ApiResponse(
            responseCode = "502",
            description =
                "Bad Gateway – an upstream service (e.g. the Pseudonym Service or "
                    + "the FHIR Storage Service) returned an error or was unreachable.",
            content = @Content(mediaType = MEDIA_TYPE_FHIR_JSON, schema = @Schema(type = "object")))
      })
  @RequestMapping(
      method = RequestMethod.POST,
      value = "${ars.context-path}$process-notification",
      consumes = {
        APPLICATION_JSON_VALUE,
        "application/json+fhir",
        "application/fhir+json",
        APPLICATION_XML_VALUE,
        "application/xml+fhir",
        "application/fhir+xml",
      },
      produces = {
        APPLICATION_JSON_VALUE,
        "application/json+fhir",
        "application/fhir+json",
        APPLICATION_XML_VALUE,
        "application/xml+fhir",
        "application/fhir+xml",
      })
  ResponseEntity<Object> fhirProcessNotificationPost(
      @NotNull
          @Parameter(
              name = "Authorization",
              description =
                  "Bearer token issued by the identity provider. "
                      + "Must be present in every request.",
              required = true,
              in = ParameterIn.HEADER,
              example = "Bearer eyJhbGciOiJSUzI1NiJ9...")
          @RequestHeader(value = "Authorization", required = true)
          String authorization,
      @NotNull
          @Parameter(
              name = "Content-Type",
              description =
                  "FHIR serialisation format of the request body. "
                      + "Supported values: application/fhir+json, application/json+fhir, "
                      + "application/json, application/fhir+xml, application/xml+fhir, "
                      + "application/xml.",
              required = true,
              in = ParameterIn.HEADER,
              schema =
                  @Schema(
                      type = "string",
                      allowableValues = {
                        "application/fhir+json",
                        "application/json+fhir",
                        "application/json",
                        "application/fhir+xml",
                        "application/xml+fhir",
                        "application/xml"
                      }))
          @RequestHeader(value = "Content-Type", required = true)
          String contentType,
      @Parameter(name = "body", required = true) @Valid @RequestBody String body,
      @Parameter(hidden = true) @RequestHeader HttpHeaders headers,
      @Parameter(hidden = true) WebRequest webRequest);
}
