spring:
  config:
    import: classpath:/base-config-application.yaml
info:
  app:
    name: '@project.name@'
    version: '@project.version@'

ars:
  outcome-issue-threshold: warning
  validation:
    url: ${DEMIS_NETWORK_VALIDATION_SERVICE_ADDRESS:http://validation-service.demis.svc.cluster.local}
  ces:
    url: ${DEMIS_NETWORK_CONTENT_ENRICHMENT_SERVICE_ADDRESS:http://context-enrichment-service.demis.svc.cluster.local}
  fss:
    url: ${DEMIS_NETWORK_FHIR_STORAGE_SERVICE_ADDRESS:http://fhir-storage-writer.demis.svc.cluster.local}
  pseudo:
    url: ${DEMIS_NETWORK_ARS_PSEUDO_SERVICE_ADDRESS:http://ars-pseudonymization-service.demis.svc.cluster.local}

feature:
  flag:
    ars_validation_enabled: false