package de.gematik.demis.ars.service.batchprocessing.entity;

/*-
 * #%L
 * Antibiotic-Resistance-Surveillance-Service
 * %%
 * Copyright (C) 2025 - 2026 gematik GmbH
 * %%
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the
 * European Commission – subsequent versions of the EUPL (the "Licence").
 * You may not use this work except in compliance with the Licence.
 *
 * You find a copy of the Licence in the "Licence" file or at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * In case of changes by gematik find details in the "Readme" file.
 *
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik,
 * find details in the "Readme" file.
 * #L%
 */

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.Immutable;

/** Stores successfully asynchronous processed notifications */
@Entity
@Immutable
@Table(name = "batch_success")
@Setter
@Getter
@ToString(callSuper = true)
public class BatchSuccessEntity extends BatchResultBase {
  /**
   * The documentId (bundle.identifier) is generated by the client. During processing this
   * identifier is replaced by a new uuid generated by demis, which the RKI only uses, and is stored
   * in this column.
   */
  @Column(nullable = false, length = 100)
  private String notificationBundleId;

  /** number of warning issues of the fhir validation. */
  @Column(nullable = false)
  private int warningCount = 0;
}
