package de.gematik.demis.ars.service.batchprocessing.entity;

/*-
 * #%L
 * Antibiotic-Resistance-Surveillance-Service
 * %%
 * Copyright (C) 2025 - 2026 gematik GmbH
 * %%
 * Licensed under the EUPL, Version 1.2 or - as soon they will be approved by the
 * European Commission – subsequent versions of the EUPL (the "Licence").
 * You may not use this work except in compliance with the Licence.
 *
 * You find a copy of the Licence in the "Licence" file or at
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expressed or implied.
 * In case of changes by gematik find details in the "Readme" file.
 *
 * See the Licence for the specific language governing permissions and limitations under the Licence.
 *
 * *******
 *
 * For additional notes and disclaimer from gematik and in case of changes by gematik,
 * find details in the "Readme" file.
 * #L%
 */

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.time.Instant;
import java.util.UUID;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * Base entity for storing the result of asynchronous processed ARS notifications of the bulk
 * upload. Note: The result of notifications from the synchronous interface are not stored
 * persistent.
 */
@MappedSuperclass
@Getter
@Setter
@ToString
public abstract class BatchResultBase {

  /** Internal technical Primary Key. Sequence generated by underlying database */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** is set via db trigger */
  @Column(insertable = false, updatable = false, nullable = false)
  private Instant createdAt;

  /** id of the batch */
  @Column(nullable = false)
  private UUID batchId;

  /** document id of the notification (bundle.identifier). Generated by the client. */
  @Column(nullable = false, length = 100)
  private String documentId;
}
